discordToken: TOKEN
guilds:
  - "GUILD ID"
sendChannel: "TEXT CHANNEL ID"
sendThread: "Thread ID"
threadChannel: "ID of channel with thread"
enableElapsedTime: false
inviteThreadOnSpeaking: false
voiceChannel: "VOICE CHANNEL ID if you want to use it on a fixed channel (or delete this)"